# Generated by Django 4.2.2 on 2023-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_floor', models.IntegerField()),
                ('is_operational', models.BooleanField(default=True)),
                ('running_status', models.CharField(choices=[('start', 'START'), ('stop', 'STOP')], default='start', max_length=50)),
                ('door_status', models.CharField(choices=[('open', 'OPEN'), ('close', 'CLOSE')], default='open', max_length=50)),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('busy', 'BUSY')], default='available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
