# Generated by Django 4.2.2 on 2023-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='direction',
            field=models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], default='up', max_length=50),
        ),
    ]
