# Generated by Django 4.2.2 on 2023-06-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0003_rename_name_elevator_elevator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='destination_floor',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField(blank=True, null=True)),
                ('destination_floor', models.IntegerField(blank=True, null=True)),
                ('door_status', models.CharField(choices=[('open', 'OPEN'), ('close', 'CLOSE')], max_length=50)),
                ('request_type', models.CharField(choices=[('door', 'DOOR'), ('elevator', 'ELEVATOR'), ('floor', 'FLOOR')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevators.elevator')),
            ],
        ),
    ]
