# Generated by Django 4.2.2 on 2023-06-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0004_elevator_destination_floor_elevatorrequest'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='elevator',
        #     name='is_operational',
        # ),
        migrations.AddField(
            model_name='elevator',
            name='working_status',
            field=models.CharField(choices=[('working', 'WORKING'), ('not_working', 'NOT WORKING'), ('in_maintenance', 'IN_MAINTENANCE')], default='working', max_length=50),
        ),
        migrations.AddField(
            model_name='elevatorrequest',
            name='working_status',
            field=models.CharField(choices=[('working', 'WORKING'), ('not_working', 'NOT WORKING'), ('in_maintenance', 'IN_MAINTENANCE')], default='working', max_length=50),
        ),
    ]
