# Generated by Django 4.2.2 on 2023-06-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0005_remove_elevator_is_operational_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='is_operational',
        ),
    ]
