# Generated by Django 4.2.2 on 2023-06-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0007_alter_elevatorrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='destination_floor',
            field=models.JSONField(default=0),
        ),
        migrations.AlterField(
            model_name='elevatorrequest',
            name='destination_floor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
