# Generated by Django 4.2.2 on 2023-06-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0009_alter_elevator_destination_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='destination_floor',
            field=models.CharField(default=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='elevatorrequest',
            name='destination_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
