# Generated by Django 4.2.2 on 2023-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0012_alter_elevator_destination_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='door_status',
            field=models.CharField(choices=[('open', 'OPEN'), ('close', 'CLOSE')], default='close', max_length=50),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='running_status',
            field=models.CharField(choices=[('start', 'START'), ('stop', 'STOP')], default='stop', max_length=50),
        ),
    ]
